### ISSUE TITLE
"heart hands" emoji 🫶 report 1 in width

### ISSUE THREAD

**Issue by erf** [hyiso/string_width#1]
I was trying out your project and found that the "heart hands" emoji 🫶 was reported as 1 in width even though it takes up two spaces in my terminal. It's part of Unicode 14.

**Comment by hyiso** [comment]
Thanks for your report, I can reproduce it locally using emoji 🫶.

It might be a bug of package [emoji_regex](https://pub.dev/packages/emoji_regex)(used by `string_width` to filter emoji Unicodes).

I've created a issue in that package https://github.com/wittyneko/emoji_regex/issues/3

**Comment by hyiso** [comment]
Also made a PR: https://github.com/wittyneko/emoji_regex/pull/4

**Comment by hyiso** [comment]
@erf try 0.1.4

**Comment by erf** [comment]
That works! Thanks for the quick reply and awesome package :)
