### ISSUE TITLE
Squares ▪︎▫︎◻︎◼︎ and arrows ◀︎▶︎ reported with width 2 but only takes up 1 space

### ISSUE THREAD

**Issue by erf** [hyiso/string_width#2]
Squares ▪︎▫︎◻︎◼︎ and arrows ◀︎▶︎ reported with width 2 but only takes up 1 space in the terminal.

There are probably more cases like this. i Pressed the "Character viewer" on my mac and went to "Bullets and stars" to find these.

**Comment by hyiso** [comment]
Emoji Regex related issue could be fired to [emoji_regex](https://github.com/wittyneko/emoji_regex/issues).
string_width@0.1.4 use a copy of emoji_regex.dart temporarily and will remove it later

**Comment by erf** [comment]
I see you replace all emoji characters with two empty spaces, is that correct though for all emoji characters? The square and arrow symbols i mentioned only took up one space, so if these are emojis as you suggest, then they would take up two spaces, but that would be wrong.

**Comment by erf** [comment]
I wrote a test and found the Unicode character for the [black square](https://unicodeplus.com/U+25AA), which is in fact part of the `emoji_regex` and is replaced with two empty chars, gives 2 in width, but in the terminals i've tested in it only takes up one column space.

```
import 'package:string_width/string_width.dart';
import 'package:test/test.dart';

void main() {
  test('measure string width of ▪', () {
    expect(stringWidth('▪'), 1);
  });
}
```
