### ISSUE TITLE
Performance for replaceAll(emojiRegex())

### ISSUE THREAD

**Issue by erf** [hyiso/string_width#4]
The following line is quite performance expensive after doing some profiling:
```
  input = input.replaceAll(emojiRegex(), '  ');
```

**Comment by hyiso** [comment]
Thanks for your report, its does not show performance cost in the unit tests, could you provide a small reproducible code?

**Comment by erf** [comment]
I guess performance is relative so not sure how much worth such a code example would provide. I just noticed in my app it was the most significant performance cost. I'm rendering a bunch of lines in the terminal and have to check all characters for width.

**Comment by erf** [comment]
But i believe you could do something smarter like checking a Unicode range or using a table lookup instead of a regex search.

**Comment by hyiso** [comment]
As noted in https://github.com/hyiso/string_width/issues/5#issuecomment-1497360990, closing this to focus on issue #5
