### ISSUE TITLE
Are all emoji characters of width 2 ?

### ISSUE THREAD

**Issue by erf** [hyiso/string_width#5]
Regarding my comment on #2 i thought i make a separate issue for this.

The following code line replaces all emoji characters with two empty spaces which returns a width of 2 as far as i can see. Is this correct behavior, or a naive implementation?

```
  input = input.replaceAll(emojiRegex(), '  ');
```

As i mentioned in #2 , the black square only takes up 1 space in the terminal whilst still being replaced in the `emojiRegex` call.

As I've learned there are lots of things determining the width of a rendered character, like the Terminal, Font, Unicode version etc. Maybe you could elaborate on the scope or correctness of this method / package.

**Comment by hyiso** [comment]
This is a good point, this package is simply migrated from JavaScript [string-wdith](https://github.com/sindresorhus/string-width), maybe  a more accurate map of emoji: width is required
